### ISSUE TITLE
What we can't do

### ISSUE THREAD

**Issue by ShempireWasTaken** [ItsBrendo/the-lost-islands#22]
Open Doors
Harvest or Collect Crops (Maybe have them replant like the trees and stone)
Kill animals (Maybe have them respawn, similar to the trees and stone)

**Comment by ItsBrendo** [comment]
Harvest Crops and Killing Animals will be available soon. I'll fix doors now if possible.

**Comment by ItsBrendo** [comment]
Doors will not be openable just yet, Will possibly need to code that in as you can open everything else such as trapdoors and what not with interact as a flag.

**Comment by ItsBrendo** [comment]
You can now kill animals, Customs drops soon.
