### ISSUE TITLE
Cooking and Crafting

### ISSUE THREAD

**Issue by ShempireWasTaken** [ItsBrendo/the-lost-islands#24]
There doesn't seem to be anywhere to cook food and smelt Ores
More importantly no where to craft, and we can't place a crafting table

**Comment by ItsBrendo** [comment]
This will be added eventually, Ill get one of the builders to place down some crafting tables and furnaces in set places.

**Comment by ItsBrendo** [comment]
Don't care who does it, but can one of you guys please do this @Changwazzer @JakeyBoi5 @gok45

**Comment by JakeyBoi5** [comment]
will do

**Comment by Changwazzer** [comment]
all of the buildings have the required item for cooking and crafting

**Comment by JakeyBoi5** [comment]
will do
